# Generated by Django 4.0.3 on 2023-01-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=50)),
                ('yetkili', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('mhz', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ram', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('watt', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='psu', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='MousePad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olcu', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mousepad', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouse', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motherboard', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('curved', models.BooleanField(default=False)),
                ('hz', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitor', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Kulaklık',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(choices=[('Siyah', 'Siyah'), ('Boş', 'Boş')], default='Boş', max_length=50)),
                ('strap_renk', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kulaklık', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Koltuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='koltuk', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Klavye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('mekanik', models.BooleanField(default=False)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klavye', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kasa', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpu', to='envanter.firma')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], default='Intel', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('seri_no', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('garanti', models.BooleanField(default=False)),
                ('garanti_bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpu', to='envanter.firma')),
            ],
        ),
    ]
