# Generated by Django 4.1.6 on 2023-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0002_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='role',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Normal', 'Normal')], default='pc', max_length=50),
        ),
    ]
