# Generated by Django 4.1.6 on 2023-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0003_pc_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='name',
            field=models.CharField(blank=True, default='PC', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='role',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Normal', 'Normal')], default='Normal', max_length=50),
        ),
    ]
