# Generated by Django 4.1.6 on 2023-03-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0004_pc_name_alter_pc_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.gpu'),
        ),
        migrations.AddField(
            model_name='pc',
            name='headset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.kulaklık'),
        ),
        migrations.AddField(
            model_name='pc',
            name='klavye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.klavye'),
        ),
        migrations.AddField(
            model_name='pc',
            name='koltuk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.koltuk'),
        ),
        migrations.AddField(
            model_name='pc',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.monitor'),
        ),
        migrations.AddField(
            model_name='pc',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.mouse'),
        ),
        migrations.AddField(
            model_name='pc',
            name='mouse_pad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.mousepad'),
        ),
    ]
