# Generated by Django 4.1.6 on 2023-03-31 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0005_pc_gpu_pc_headset_pc_klavye_pc_koltuk_pc_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kulaklık',
            name='model',
            field=models.CharField(default='Boş', max_length=50),
        ),
        migrations.AlterField(
            model_name='kulaklık',
            name='strap_renk',
            field=models.CharField(blank=True, choices=[('Siyah', 'Siyah'), ('Boş', 'Boş')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.cpu'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.motherboard'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='psu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.psu'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='role',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Normal', 'Normal'), ('Yedek', 'Yedek'), ('Hurda', 'Hurda')], default='Normal', max_length=50),
        ),
    ]
