# Generated by Django 4.1.6 on 2023-03-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0006_pc_notes_alter_kulaklık_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='ram',
        ),
        migrations.AddField(
            model_name='pc',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='envanter.ram'),
        ),
    ]
